name: H3xWhitelist
version: '1.1'
main: me.h3xty.h3xWhitelist.H3xWhitelist
api-version: '1.21'
authors: [ H3xty ]
description: Name based whitelist
permissions:
  h3xwhitelist:
    description: Manage whitelist
    default: op
